DELIMITER  //
CREATE PROCEDURE GuardarProductoAlmacen(IN _PRODUCTO_NO INTEGER(4), IN  UNIDADES INTEGER(4))
BEGIN
update productos set STOCK_DISPONIBLE = STOCK_DISPONIBLE+UNIDADES where PRODUCTO_NO=_PRODUCTO_NO;
 END //
DELIMITER ;